<?php if(Mage::registry('current_product')): ?>
<?php $product = Mage::registry('current_product'); ?>
        <meta property="og:title" content="<?php echo ($product->getName()); ?>" />
        <meta property="og:type" content="product" />
        <meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>" />
        <meta property="og:url" content="<?php echo Mage::registry('product')->getProductUrl(); ?>" />
        <meta property="og:description" content="<?php echo strip_tags(($product->getShortDescription())); ?>" />
        <meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php endif;?>
